server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka/

spring:
  application:
    name: yipai-zuul
  servlet:
    multipart:
      enabled: true
      max-request-size: 100Mb
      max-file-size: 10Mb

zuul:
  routes:
    api-user:
      path: /userService/**
      serviceId: service-user
    api-web:
      path: /webService/**
      serviceId: service-web
  host:
    socket-timeout-millis: 100000
    connect-timeout-millis: 100000

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
