server:
  port: 8180
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka/
spring:
  application:
    name: service-user
  boot:
    admin:
      client:
        url: "http://localhost:8081"
  datasource:
    username: root
    password: 15357886708
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yipai?useUnicode=true&characterEncoding=utf8
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 106.15.178.88
    port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 100Mb
      max-request-size: 100Mb
  rabbitmq:
    host: 106.15.178.88
    port: 5672
    username: user_admin
    password: passwd_admin
    virtual-host: /
    publisher-confirms: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#展示sql
logging:
  level:
    com.hzc.serviceuser.**: DEBUG

# 管理端配置
management:
  endpoints:
    web:
      exposure:
        include: "*"

aliyunOss:
  accesskeyId: LTAIeQHdzxxgMPoq
  accessKeySecret: ANAoBY5dS5UazepqCucSrVAC5eb4yd
  bucketName: hzcbysj
  endPoint: oss-cn-beijing.aliyuncs.com
  callbackUrl: http://hzcbysj.oss-cn-beijing.aliyuncs.com/
  