server:
  port: 8180
eureka:
  instance:
    ip-address: 106.15.178.88
  client:
    service-url:
      defaultZone: http://106.13.147.166:8088/eureka/
spring:
  application:
    name: service-user
  datasource:
    username: root
    password: 15357886708
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.13.147.166:3306/yipai?useUnicode=true&characterEncoding=utf8
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 106.15.178.88
    port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 100Mb
      max-request-size: 100Mb
  rabbitmq:
    host: 106.15.178.88
    port: 5672
    username: user_admin
    password: passwd_admin
    virtual-host: /
    publisher-confirms: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#展示sql
logging:
  level:
    com.hzc.serviceuser.**: DEBUG


# 管理端配置
management:
  endpoints:
    web:
      exposure:
        include: "*"

aliyunOss:
  accesskeyId: LTAIeQHdzxxgMPoq
  accessKeySecret: ANAoBY5dS5UazepqCucSrVAC5eb4yd
  bucketName: hzcbysj
  endPoint: oss-cn-beijing.aliyuncs.com
  callbackUrl: http://hzcbysj.oss-cn-beijing.aliyuncs.com/

mybatis-plus:
    mapper-locations: classpath:mybatis/mapper/*.xml
    type-aliases-package: com.hzc.serviceuser.entity.GoodsComent
    global-config:
      db-config:
        #主键插入策略
        id-type: auto
        #非空判断
        field-strategy: ignored
        table-underline: true
    configuration:
      #结果返回给VO时无需使用AS匹配 直接返回驼峰
      map-underscore-to-camel-case: true
    check-config-location: false


