server:
  port: 8181
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
spring:
  application:
    name: service-web
  boot:
    admin:
      client:
        url: "http://localhost:8081"
  datasource:
    username: root
    password: 15357886708
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yipai?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 100Mb
      max-request-size: 100Mb
  rabbitmq:
    host: 106.15.178.88
    port: 5672
    username: user_admin
    password: passwd_admin
    publisher-confirms: true
  data:
    elasticsearch:
      cluster-nodes: 106.15.178.88:9300
      cluster-name: search
  mail:
    host: smtp.qq.com
    username: 1220820912@qq.com
    password: phodpqrurvphiddb
    port: 587

logging:
  level:
    com.hzc.serviceuser.**: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
mybatis:
  mapper-locations: classpath:mybatis/*.xml